/**
 * Internationalization (i18n) system for multi-language report support.
 * Supports Traditional Chinese (Taiwan) and English.
 */

export type Locale = 'zh-TW' | 'en';

/**
 * Translation strings for the report.
 */
export interface TranslationStrings {
  // Report sections
  'report.title': string;
  'report.generatedOn': string;
  'report.healthScore': string;
  'report.executiveSummary': string;
  'report.priorityActions': string;
  'report.priorityActionsDesc': string;
  'report.detailedAnalysis': string;
  'report.detailedAnalysisDesc': string;
  'report.noIssues': string;
  'report.noIssuesDesc': string;
  'report.issueSummary': string;
  'report.generatedBy': string;

  // Methodology section
  'methodology.title': string;
  'methodology.toolsTitle': string;
  'methodology.toolsDesc': string;
  'methodology.testsTitle': string;
  'methodology.testConditions': string;
  'methodology.testConditionsNote': string;
  'methodology.issuesFound': string;

  // Category names
  'category.seo': string;
  'category.seoDesc': string;
  'category.performance': string;
  'category.performanceDesc': string;
  'category.security': string;
  'category.securityDesc': string;

  // Severity levels
  'severity.critical': string;
  'severity.high': string;
  'severity.medium': string;
  'severity.low': string;
  'severity.info': string;

  // Fix difficulty
  'difficulty.low': string;
  'difficulty.medium': string;
  'difficulty.high': string;

  // Issue table labels
  'issue.category': string;
  'issue.businessImpact': string;
  'issue.expectedOutcome': string;
  'issue.fixDifficulty': string;
  'issue.recommendation': string;
  'issue.affectedUrl': string;

  // Performance test specs
  'testSpec.desktop': string;
  'testSpec.mobile4g': string;

  // Navigation hints (slide mode)
  'nav.hint': string;
}

/**
 * Translations for each locale.
 */
export const translations: Record<Locale, TranslationStrings> = {
  'zh-TW': {
    // Report sections
    'report.title': '網站審計報告',
    'report.generatedOn': '報告產生時間',
    'report.healthScore': '健康分數',
    'report.executiveSummary': '執行摘要',
    'report.priorityActions': '優先處理事項',
    'report.priorityActionsDesc': '以下事項依照業務影響和修復難度進行優先排序：',
    'report.detailedAnalysis': '詳細問題分析',
    'report.detailedAnalysisDesc': '發現 {{count}} 個問題。問題依嚴重程度和業務影響排序。',
    'report.noIssues': '未發現問題！',
    'report.noIssuesDesc': '您的網站通過了所有審計檢查。',
    'report.issueSummary': '問題統計',
    'report.generatedBy': '由 web-audit-cli 產生',

    // Methodology section
    'methodology.title': '審計方法論',
    'methodology.toolsTitle': '使用工具',
    'methodology.toolsDesc': '本次審計使用業界標準的開源工具，這些工具獲得全球網頁開發社群的認可：',
    'methodology.testsTitle': '執行測試',
    'methodology.testConditions': '效能測試條件',
    'methodology.testConditionsNote': '測試結果可能因網路和設備條件不同而有所差異。',
    'methodology.issuesFound': '發現問題數',

    // Category names
    'category.seo': 'SEO',
    'category.seoDesc': '搜尋引擎最佳化',
    'category.performance': '效能',
    'category.performanceDesc': '速度與效率',
    'category.security': '安全性',
    'category.securityDesc': '安全與防護',

    // Severity levels
    'severity.critical': '嚴重',
    'severity.high': '高',
    'severity.medium': '中',
    'severity.low': '低',
    'severity.info': '資訊',

    // Fix difficulty
    'difficulty.low': '低',
    'difficulty.medium': '中',
    'difficulty.high': '高',

    // Issue table labels
    'issue.category': '類別',
    'issue.businessImpact': '業務影響',
    'issue.expectedOutcome': '預期效果',
    'issue.fixDifficulty': '修復難度',
    'issue.recommendation': '建議',
    'issue.affectedUrl': '受影響網址',

    // Performance test specs
    'testSpec.desktop': '桌面版，無節流',
    'testSpec.mobile4g': '行動版 4G，已節流',

    // Navigation hints (slide mode)
    'nav.hint': '使用 ↑↓ 方向鍵或滾動瀏覽',
  },

  en: {
    // Report sections
    'report.title': 'Web Audit Report',
    'report.generatedOn': 'Generated on',
    'report.healthScore': 'Health Score',
    'report.executiveSummary': 'Executive Summary',
    'report.priorityActions': 'Priority Actions',
    'report.priorityActionsDesc':
      'The following actions are prioritized based on business impact and implementation effort:',
    'report.detailedAnalysis': 'Detailed Issue Analysis',
    'report.detailedAnalysisDesc':
      'Found {{count}} issues across all categories. Issues are sorted by severity and business impact.',
    'report.noIssues': 'No issues found!',
    'report.noIssuesDesc': 'Your website passed all audit checks.',
    'report.issueSummary': 'Issue Summary',
    'report.generatedBy': 'Generated by web-audit-cli',

    // Methodology section
    'methodology.title': 'Audit Methodology',
    'methodology.toolsTitle': 'Tools Used',
    'methodology.toolsDesc':
      'This audit was conducted using industry-standard, open-source tools recognized by the global web development community:',
    'methodology.testsTitle': 'Tests Performed',
    'methodology.testConditions': 'Performance Test Conditions',
    'methodology.testConditionsNote':
      'Results may vary under different network and device conditions.',
    'methodology.issuesFound': 'Issues found',

    // Category names
    'category.seo': 'SEO',
    'category.seoDesc': 'Search Optimization',
    'category.performance': 'Performance',
    'category.performanceDesc': 'Speed & Efficiency',
    'category.security': 'Security',
    'category.securityDesc': 'Safety & Protection',

    // Severity levels
    'severity.critical': 'Critical',
    'severity.high': 'High',
    'severity.medium': 'Medium',
    'severity.low': 'Low',
    'severity.info': 'Info',

    // Fix difficulty
    'difficulty.low': 'Low',
    'difficulty.medium': 'Medium',
    'difficulty.high': 'High',

    // Issue table labels
    'issue.category': 'Category',
    'issue.businessImpact': 'Business Impact',
    'issue.expectedOutcome': 'Expected Outcome',
    'issue.fixDifficulty': 'Fix Difficulty',
    'issue.recommendation': 'Recommendation',
    'issue.affectedUrl': 'Affected URL',

    // Performance test specs
    'testSpec.desktop': 'Desktop, No Throttling',
    'testSpec.mobile4g': 'Mobile 4G, Throttled',

    // Navigation hints (slide mode)
    'nav.hint': 'Use ↑↓ arrows or scroll to navigate',
  },
};

/**
 * Create a translator function for a specific locale.
 */
export function createTranslator(
  locale: Locale
): (key: keyof TranslationStrings, params?: Record<string, string | number>) => string {
  return (key: keyof TranslationStrings, params?: Record<string, string | number>) => {
    let text = translations[locale][key] || translations['en'][key] || key;

    // Replace template parameters like {{count}}
    if (params) {
      for (const [param, value] of Object.entries(params)) {
        text = text.replace(new RegExp(`\\{\\{${param}\\}\\}`, 'g'), String(value));
      }
    }

    return text;
  };
}

/**
 * Get the default locale.
 */
export function getDefaultLocale(): Locale {
  return 'en';
}

/**
 * Validate and normalize a locale string.
 */
export function normalizeLocale(locale: string): Locale {
  const normalized = locale.toLowerCase();
  if (normalized === 'zh-tw' || normalized === 'zh' || normalized === 'chinese') {
    return 'zh-TW';
  }
  return 'en';
}
